WebObligatorio/Controllers/CompraController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Dominio;

namespace WebObligatorio.Controllers
{
    public class CompraController : Controller
    {
        Sistema s = Sistema.GetInstancia(); 
        public IActionResult ComprasMayores()
        {
            if (HttpContext.Session.GetString("LogRol") == "Operador")
            {
                ViewBag.unaC = s.ComprasMayorValor(); 
                return View();
            }
            else
            {
                return RedirectToAction("Login","Login");
            }
        }
        public IActionResult ComprasEntreFechas()
        {
            if (HttpContext.Session.GetString("LogRol") == "Operador")
            {
                return View();
            } else
            {
                return RedirectToAction("Login", "Login");
            }
        }
        [HttpPost]
        public IActionResult ComprasEntreFechas(DateTime desde, DateTime hasta)
        {
            ViewBag.unaC = s.CompraEntreFechas(desde, hasta); 
            ViewBag.Total = s.MontoTotalCompras(s.CompraEntreFechas(desde, hasta));
            if(ViewBag.unaC.Count == 0)
            {
                ViewBag.Respuesta = "No se han podido encontrar compras entre el rango de fechas dado";
            }
            return View();
        }
        public IActionResult CompraSegunCliente()
        {
            if (HttpContext.Session.GetString("LogRol") == "Cliente")
            {
                string nombreUserLog = HttpContext.Session.GetString("LogNombre");
                ViewBag.CompraCliente = s.CompraSegunCliente(nombreUserLog); 
                return View();
            }else
            {
                return RedirectToAction("Login", "Login");
            }
        }
        public IActionResult BuscarCompra()
        {
            if (HttpContext.Session.GetString("LogRol") == "Cliente")
            {
                return View();
            } else
            {
                return RedirectToAction("Login", "Login");
            }
        }
        [HttpPost]
        public IActionResult BuscarCompra(int id)
        {
            string nombreUserLog = HttpContext.Session.GetString("LogNombre");
            ViewBag.unaC = s.BuscarCompra(id,nombreUserLog);
            if(ViewBag.unaC == null)
            {
                ViewBag.Resultado= "No se ah podido encontrar ninguna compra con ese numero, ingreselo correctamente y vuelva a intentarlo";
            }
            return View();
        }
        public IActionResult CancelarCompra(int id)
        {
            if (HttpContext.Session.GetString("LogRol") == "Cliente")
            {
                bool cancelarCompra = s.CancelarCompra(id); 
                if (cancelarCompra)
                {
                    ViewBag.ResultadoOk = "La compra se cancelo correctamente";
                }
                else
                {
                    ViewBag.ResultadoError = "La cancelacion solo se puede realizar si esta comprendida dentro del plazo de 24 horas antes de la realizacion de la Actividad." +
                                                    "Plazo maximo exedido, no se ah podido llevar a cabo la cancelacion";
                }
                return View();
            } else
            {
                return RedirectToAction("Login", "Login");
            }
        }
        public IActionResult ComprarActividad()
        {
            if (HttpContext.Session.GetString("LogRol") == "Cliente")
            {
                return View();
            } else
            {
                return RedirectToAction("Login","Login");
            }
        }
        [HttpPost]
        public IActionResult ComprarActividad(string NombreAct,int cantidadEntradas)
        {
            string nombreUserLog = HttpContext.Session.GetString("LogNombre");
            Actividad unaA = s.BuscarActividad(NombreAct);
            Usuario unUser = s.BuscarUsuario(nombreUserLog);  
            bool unaC = s.AgregarCompra(cantidadEntradas, unaA, unUser, DateTime.Now); 
            if (unaC)
            {
                ViewBag.ResultadoOk = "La compra se ah realizado con exito";
            }
            else
            {     
                ViewBag.ResultadoError = "La compra no se ah podido realizar, verifique si ingreso los datos correctamente";
            }
            return View();
        }
        public IActionResult ComprarEntradas()
        {
            if (HttpContext.Session.GetString("LogRol") == "Cliente")
            {
                ViewBag.Act = s.Actividades;
                ViewBag.User = s.Usuarios;
                return View();
            }else {
                return RedirectToAction("Login", "Login");
            }
        }
        [HttpPost]
        public IActionResult ComprarEntradas(string nombreActividad, int cantidadEntradas)
        {
            ViewBag.Act = s.Actividades;
            ViewBag.User = s.Usuarios;
            string nombreUserLog = HttpContext.Session.GetString("LogNombre");
            Actividad unaA = s.BuscarActividad(nombreActividad);
            Usuario unUser = s.BuscarUsuario(nombreUserLog);   
            bool unaC = s.AgregarCompra(cantidadEntradas, unaA, unUser, DateTime.Now); 
            if (unaC)
            {
                ViewBag.ResultadoOk = "La compra se ah realizado con exito";
            }
            else
            {
                ViewBag.ResultadoError = "La compra no se ah podido realizar";
            }
            return View();
        }

    }
}

WebObligatorio/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Dominio;

namespace WebObligatorio.Controllers
{
    public class UsuarioController : Controller
    {
        Sistema s = Sistema.GetInstancia();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AltaUsuario()
        {
            if (HttpContext.Session.GetString("LogRol") == "SinIdentificar")
            {
                return View(new Usuario());
            } else
            {
               return RedirectToAction("Login", "Login");
            }
        }
        [HttpPost]
        public IActionResult AltaUsuario(string nombre, string apellido, string email, DateTime fechaNacimiento,string nombreUsuario, string contraseña)
        {
            string nombreUsuarioLog = HttpContext.Session.GetString("LogNombre");
            Usuario usuarioEditado = s.BuscarUsuario(nombreUsuarioLog);
            bool editado = false;  
                 editado = s.EditarUsuario(usuarioEditado, nombre, apellido,email,fechaNacimiento, nombreUsuario, contraseña); 

            if (editado == true)
                {          
                ViewBag.ResultadoOk = "¡Usted se registro correctamente como Cliente!";
                }
                else
                {
                ViewBag.nombre = nombre;
                ViewBag.apellido = apellido;
                ViewBag.email = email;
                ViewBag.fechaNacimiento = fechaNacimiento.ToString("yyyy-MM-dd");
                ViewBag.nombreUsuario = nombreUsuario;
                ViewBag.ResultadoError = "¡No se ah podido registrar, ingrese los datos correctamente!";
                }           
            return View();
        }
        public IActionResult AltaUsuarioSinIdentificar()
        {      
            return View();     
        }
        [HttpPost]
        public IActionResult AltaUsuarioSinIdentificar(string nombreUsuario, string contraseña)
        {    
            Usuario usuarioEditado = s.AgregarUsuarioSinIdentificar(nombreUsuario, contraseña);
            
                if (usuarioEditado != null)
                {
                    ViewBag.ResultadoOk = "¡Usted se registro correctamente!";
                }
                else
                {        
                    ViewBag.nombreUsuario = nombreUsuario;
                    ViewBag.ResultadoError = "¡No se ah podido registrar, ingrese los datos correctamente!. La contraseña debe tener una minuscula, una mayuscula y un digito como minimo.";
                }
            return View();
        }
        public IActionResult ListaUsuario()
        {
            if (HttpContext.Session.GetString("LogRol") == "Operador")
            {
                ViewBag.ListaUsuarios = s.ClientesOrdenados();
                return View();
            } else
            {
                return RedirectToAction("Login", "Login");
            }
        }
        public IActionResult Bienvenida()
        {
            

            if (HttpContext.Session.GetString("LogRol") == "SinIdentificar" || HttpContext.Session.GetString("LogRol") == "Cliente" ||
                HttpContext.Session.GetString("LogRol") == "Operador")
            {
                string nombreUsuarioLog = HttpContext.Session.GetString("LogNombre");
                Usuario User = s.BuscarUsuario(nombreUsuarioLog);
                return View(User);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }

    }
}

WebObligatorio/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebObligatorio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav>
            <div class="container">          
                <ul>
                    @if (Context.Session.GetString("LogRol") == "SinIdentificar")
                    {
                        <!-- Usuario Sin Identificar -->
                        <li>
                            <a asp-area="" asp-controller="Actividad" asp-action="ListarActividades">Lista de Actividades</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Usuario" asp-action="AltaUsuario">Registro</a>
                        </li>
                    }
                    else if (Context.Session.GetString("LogRol") == "Cliente")
                    {
                        <!-- Usuario Cliente -->
                        <li>
                            <a asp-area="" asp-controller="Actividad" asp-action="ListActCompra">Compra de Actividades</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Compra" asp-action="ComprarEntradas">Comprar Entradas</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Compra" asp-action="CompraSegunCliente">Compras Personales</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Compra" asp-action="BuscarCompra">Cancelar Compra</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Actividad" asp-action="ListActMeGusta">Likes Actividades</a>
                        </li>
                    }
                    else if (Context.Session.GetString("LogRol") == "Operador")
                    {
                        <!-- Usuario Operador -->

                        <li>
                            <a asp-area="" asp-controller="Compra" asp-action="ComprasEntreFechas">Compra entre Fechas</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Usuario" asp-action="ListaUsuario">Lista de Usuarios </a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Actividad" asp-action="SegunLugar">Buscar Actividad por Lugar</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Actividad" asp-action="SegunCatFecha">Act. por Categoria y Fecha</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Compra" asp-action="ComprasMayores">Compras Mayores</a>
                        </li>
                    }

                    @if (   Context.Session.GetString("LogRol") == "SinIdentificar" ||
                            Context.Session.GetString("LogRol") == "Cliente" ||
                            Context.Session.GetString("LogRol") == "Operador")
                    {
                        <li>
                            <a asp-area="" asp-controller="Login" asp-action="LogOut">Salir</a>
                        </li>
                    }
                </ul>         
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebObligatorio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>